-- Create MEMBER_COACH table for coach-member assignments
CREATE TABLE IF NOT EXISTS MEMBER_COACH (
    MEMBER_ID SMALLINT NOT NULL,
    COACH_ID SMALLINT NOT NULL,
    ASSIGNED_DATE DATE DEFAULT CURRENT_DATE() NOT NULL,
    PRIMARY KEY (MEMBER_ID, COACH_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES `MEMBER`(MEMBER_ID),
    FOREIGN KEY (COACH_ID) REFERENCES COACH(COACH_ID)
);
